version: "3.9"

services:

  ingestion:
    build: ./docker
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    environment:
      - YEAR=2025
      - MONTH=01
    command: python jobs/data_ingestion.py

  cleaning:
    build: ./docker
    depends_on:
      ingestion:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python jobs/data_cleaning.py

  quality:
    build: ./docker
    depends_on:
      cleaning:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python jobs/data_quality.py

  supervised_machine_learning:
    build: ./docker
    depends_on:
      quality:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python jobs/data_supervised_learning.py


  unsupervised_machine_learning:
    build: ./docker
    depends_on:
      quality:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python jobs/data_unsupervised_learning.py

  visualization:
    build: ./docker
    depends_on:
      quality:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python jobs/data_visualization.py
