version: "3.9"

services:

  ingestion:
    build: ./docker/python/
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    environment:
      - YEAR=2025
      - MONTH=01
    command: python jobs/data_ingestion.py

  cleaning:
    build: ./docker/python/
    depends_on:
      ingestion:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python jobs/data_cleaning.py

  quality:
    build: ./docker/python/
    depends_on:
      cleaning:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python jobs/data_quality.py

  deep_learning:
    build: ./docker/tensorflow/
    depends_on:
      quality:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
      - ./jobs:/app/jobs
    command: python -u jobs/data_deep_learning.py